import React, { forwardRef } from 'react';
import {
  AlertCircle,
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  BarChart,
  BarChart2,
  BarChart3,
  Bell,
  Book,
  BookOpen,
  Building2,
  Calendar,
  CalendarDays,
  CalendarRange,
  Check,
  CheckCircle,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  ClipboardCheck,
  Clock,
  Compass,
  Download,
  Edit,
  Edit3,
  ExternalLink,
  Eye,
  EyeOff,
  FileText,
  Filter,
  FolderHeart,
  GraduationCap,
  Heart,
  HelpCircle,
  Home,
  Info,
  Landmark,
  Layers,
  Library,
  Lightbulb,
  Lock,
  LogOut,
  Mail,
  MapPin,
  Menu,
  Moon,
  MoreHorizontal,
  MoreVertical,
  Palette,
  Paperclip,
  PenLine,
  Plus,
  Printer,
  RefreshCw,
  Search,
  Settings,
  Shield,
  ShieldCheck,
  Sparkles,
  Sprout,
  Star,
  Sun,
  Trash,
  Trash2,
  Unlock,
  Upload,
  User,
  UserPlus,
  Users,
  X,
  XCircle,
  type LucideIcon,
} from 'lucide-react';

export type StandardIconSize = 'sm' | 'md' | 'lg' | 'xl';
export type IconSize = StandardIconSize | number;

export const ICON_SIZES: Record<StandardIconSize, number> = {
  sm: 16,
  md: 20,
  lg: 24,
  xl: 32,
};

const BASE_ICON_REGISTRY: Record<string, LucideIcon> = {
  // Standard UI icons
  home: Home,
  users: Users,
  'book-open': BookOpen,
  library: Library,
  'calendar-days': CalendarDays,
  calendar: Calendar,
  'calendar-range': CalendarRange,
  'pen-line': PenLine,
  'folder-heart': FolderHeart,
  'clipboard-check': ClipboardCheck,
  'bar-chart-3': BarChart3,
  'bar-chart-2': BarChart2,
  'bar-chart': BarChart,
  palette: Palette,
  settings: Settings,
  'log-out': LogOut,
  'chevron-down': ChevronDown,
  'chevron-right': ChevronRight,
  'chevron-left': ChevronLeft,
  'chevron-up': ChevronUp,
  menu: Menu,
  x: X,
  bell: Bell,
  plus: Plus,
  search: Search,
  check: Check,
  'check-circle': CheckCircle,
  'check-circle-2': CheckCircle2,
  'alert-triangle': AlertTriangle,
  'alert-circle': AlertCircle,
  info: Info,
  clock: Clock,
  sparkles: Sparkles,
  'graduation-cap': GraduationCap,
  heart: Heart,
  shield: Shield,
  'shield-check': ShieldCheck,
  'file-text': FileText,
  layers: Layers,
  compass: Compass,
  'trash-2': Trash2,
  trash: Trash,
  'edit-3': Edit3,
  edit: Edit,
  filter: Filter,
  'external-link': ExternalLink,
  'refresh-cw': RefreshCw,
  user: User,
  'user-plus': UserPlus,
  sun: Sun,
  moon: Moon,
  download: Download,
  upload: Upload,
  'arrow-right': ArrowRight,
  'arrow-left': ArrowLeft,
  lock: Lock,
  unlock: Unlock,
  eye: Eye,
  'eye-off': EyeOff,
  'more-vertical': MoreVertical,
  'more-horizontal': MoreHorizontal,
  'building-2': Building2,
  landmark: Landmark,
  sprout: Sprout,
  'map-pin': MapPin,
  mail: Mail,
  book: Book,
  printer: Printer,
  star: Star,
  paperclip: Paperclip,
  lightbulb: Lightbulb,
  circle: Circle,
  'x-circle': XCircle,
  'help-circle': HelpCircle,

  // Domain aliases
  learners: Users,
  devotional: BookOpen,
  curriculum: Library,
  schedule: Calendar,
  records: FileText,
  portfolio: FolderHeart,
  attendance: ClipboardCheck,
  reports: BarChart3,

  // PascalCase & camelCase aliases
  Home: Home,
  Users: Users,
  BookOpen: BookOpen,
  bookOpen: BookOpen,
  Library: Library,
  CalendarDays: CalendarDays,
  calendarDays: CalendarDays,
  Calendar: Calendar,
  CalendarRange: CalendarRange,
  calendarRange: CalendarRange,
  PenLine: PenLine,
  penLine: PenLine,
  FolderHeart: FolderHeart,
  folderHeart: FolderHeart,
  ClipboardCheck: ClipboardCheck,
  clipboardCheck: ClipboardCheck,
  BarChart3: BarChart3,
  barChart3: BarChart3,
  BarChart2: BarChart2,
  barChart2: BarChart2,
  BarChart: BarChart,
  barChart: BarChart,
  Palette: Palette,
  Settings: Settings,
  LogOut: LogOut,
  logOut: LogOut,
  ChevronDown: ChevronDown,
  chevronDown: ChevronDown,
  ChevronRight: ChevronRight,
  chevronRight: ChevronRight,
  ChevronLeft: ChevronLeft,
  chevronLeft: ChevronLeft,
  ChevronUp: ChevronUp,
  chevronUp: ChevronUp,
  Menu: Menu,
  X: X,
  Bell: Bell,
  Plus: Plus,
  Search: Search,
  Check: Check,
  CheckCircle: CheckCircle,
  checkCircle: CheckCircle,
  CheckCircle2: CheckCircle2,
  checkCircle2: CheckCircle2,
  AlertTriangle: AlertTriangle,
  alertTriangle: AlertTriangle,
  AlertCircle: AlertCircle,
  alertCircle: AlertCircle,
  Info: Info,
  Clock: Clock,
  Sparkles: Sparkles,
  GraduationCap: GraduationCap,
  graduationCap: GraduationCap,
  Heart: Heart,
  Shield: Shield,
  ShieldCheck: ShieldCheck,
  shieldCheck: ShieldCheck,
  FileText: FileText,
  fileText: FileText,
  Layers: Layers,
  Compass: Compass,
  Trash2: Trash2,
  trash2: Trash2,
  Trash: Trash,
  Edit3: Edit3,
  edit3: Edit3,
  Edit: Edit,
  Filter: Filter,
  ExternalLink: ExternalLink,
  externalLink: ExternalLink,
  RefreshCw: RefreshCw,
  refreshCw: RefreshCw,
  User: User,
  UserPlus: UserPlus,
  userPlus: UserPlus,
  Sun: Sun,
  Moon: Moon,
  Download: Download,
  Upload: Upload,
  ArrowRight: ArrowRight,
  arrowRight: ArrowRight,
  ArrowLeft: ArrowLeft,
  arrowLeft: ArrowLeft,
  Lock: Lock,
  Unlock: Unlock,
  Eye: Eye,
  EyeOff: EyeOff,
  eyeOff: EyeOff,
  MoreVertical: MoreVertical,
  moreVertical: MoreVertical,
  MoreHorizontal: MoreHorizontal,
  moreHorizontal: MoreHorizontal,
  Building2: Building2,
  building2: Building2,
  Landmark: Landmark,
  Sprout: Sprout,
  MapPin: MapPin,
  mapPin: MapPin,
  Mail: Mail,
  Book: Book,
  Printer: Printer,
  Star: Star,
  Paperclip: Paperclip,
  Lightbulb: Lightbulb,
  Circle: Circle,
  XCircle: XCircle,
  xCircle: XCircle,
  HelpCircle: HelpCircle,
  helpCircle: HelpCircle,
  Learners: Users,
  Devotional: BookOpen,
  Curriculum: Library,
  Schedule: Calendar,
  Records: FileText,
  Portfolio: FolderHeart,
  Attendance: ClipboardCheck,
  Reports: BarChart3,
};

export const ICON_NAMES = [
  'home',
  'users',
  'book-open',
  'library',
  'calendar-days',
  'calendar',
  'calendar-range',
  'pen-line',
  'folder-heart',
  'clipboard-check',
  'bar-chart-3',
  'bar-chart-2',
  'bar-chart',
  'palette',
  'settings',
  'log-out',
  'chevron-down',
  'chevron-right',
  'chevron-left',
  'chevron-up',
  'menu',
  'x',
  'bell',
  'plus',
  'search',
  'check',
  'check-circle',
  'check-circle-2',
  'alert-triangle',
  'alert-circle',
  'info',
  'clock',
  'sparkles',
  'graduation-cap',
  'heart',
  'shield',
  'shield-check',
  'file-text',
  'layers',
  'compass',
  'trash-2',
  'trash',
  'edit-3',
  'edit',
  'filter',
  'external-link',
  'refresh-cw',
  'user',
  'user-plus',
  'sun',
  'moon',
  'download',
  'upload',
  'arrow-right',
  'arrow-left',
  'lock',
  'unlock',
  'eye',
  'eye-off',
  'more-vertical',
  'more-horizontal',
  'building-2',
  'landmark',
  'sprout',
  'map-pin',
  'mail',
  'book',
  'printer',
  'star',
  'paperclip',
  'lightbulb',
  'circle',
  'x-circle',
  'help-circle',
  'learners',
  'devotional',
  'curriculum',
  'schedule',
  'records',
  'portfolio',
  'attendance',
  'reports',
  'Home',
  'Users',
  'BookOpen',
  'Library',
  'CalendarDays',
  'Calendar',
  'CalendarRange',
  'PenLine',
  'FolderHeart',
  'ClipboardCheck',
  'BarChart3',
  'BarChart2',
  'BarChart',
  'Palette',
  'Settings',
  'LogOut',
  'ChevronDown',
  'ChevronRight',
  'ChevronLeft',
  'ChevronUp',
  'Menu',
  'X',
  'Bell',
  'Plus',
  'Search',
  'Check',
  'CheckCircle',
  'CheckCircle2',
  'AlertTriangle',
  'AlertCircle',
  'Info',
  'Clock',
  'Sparkles',
  'GraduationCap',
  'Heart',
  'Shield',
  'ShieldCheck',
  'FileText',
  'Layers',
  'Compass',
  'Trash2',
  'Trash',
  'Edit3',
  'Edit',
  'Filter',
  'ExternalLink',
  'RefreshCw',
  'User',
  'UserPlus',
  'Sun',
  'Moon',
  'Download',
  'Upload',
  'ArrowRight',
  'ArrowLeft',
  'Lock',
  'Unlock',
  'Eye',
  'EyeOff',
  'MoreVertical',
  'MoreHorizontal',
  'Building2',
  'Landmark',
  'Sprout',
  'MapPin',
  'Mail',
  'Book',
  'Printer',
  'Star',
  'Paperclip',
  'Lightbulb',
  'Circle',
  'XCircle',
  'HelpCircle',
  'Learners',
  'Devotional',
  'Curriculum',
  'Schedule',
  'Records',
  'Portfolio',
  'Attendance',
  'Reports',
] as const;

export type IconName = (typeof ICON_NAMES)[number] | (string & {});

function resolveIcon(name: string): LucideIcon {
  if (BASE_ICON_REGISTRY[name]) {
    return BASE_ICON_REGISTRY[name];
  }

  // Normalize kebab-case to camelCase / PascalCase or vice-versa
  const cleaned = name.toLowerCase().replace(/[-_]/g, '');
  for (const [key, icon] of Object.entries(BASE_ICON_REGISTRY)) {
    if (key.toLowerCase().replace(/[-_]/g, '') === cleaned) {
      return icon;
    }
  }

  return HelpCircle;
}

function resolveSize(size: IconSize | undefined): number {
  if (typeof size === 'number') {
    return size;
  }
  if (size && size in ICON_SIZES) {
    return ICON_SIZES[size as StandardIconSize];
  }
  return ICON_SIZES.md;
}

export interface AletheiaIconProps extends React.SVGAttributes<SVGSVGElement> {
  name: IconName;
  size?: IconSize;
  className?: string;
  color?: string;
  strokeWidth?: number;
  label?: string;
  'aria-label'?: string;
  'aria-hidden'?: boolean | 'true' | 'false';
  role?: string;
  'data-testid'?: string;
}

export const AletheiaIcon = forwardRef<SVGSVGElement, AletheiaIconProps>(
  (
    {
      name,
      size = 'md',
      className = '',
      color,
      strokeWidth = 2,
      label,
      'aria-label': ariaLabel,
      'aria-hidden': ariaHidden,
      role,
      'data-testid': testId,
      ...restProps
    },
    ref
  ) => {
    const Component = resolveIcon(name);
    const pixelSize = resolveSize(size);

    const effectiveLabel = label || ariaLabel;
    const isSemantic = Boolean(effectiveLabel || role === 'img');

    const effectiveRole = role ?? (isSemantic ? 'img' : undefined);
    const effectiveAriaHidden =
      ariaHidden !== undefined
        ? ariaHidden
        : isSemantic
          ? undefined
          : 'true';

    const mergedClassName = `ui-icon ${className}`.trim();

    return (
      <Component
        ref={ref}
        size={pixelSize}
        color={color}
        strokeWidth={strokeWidth}
        className={mergedClassName}
        role={effectiveRole}
        aria-label={effectiveLabel}
        aria-hidden={effectiveAriaHidden}
        data-testid={testId}
        {...restProps}
      />
    );
  }
);

AletheiaIcon.displayName = 'AletheiaIcon';
