export interface CountryOption {
  code: string;
  name: string;
}

/**
 * Standard ISO 3166-1 alpha-3 country list with Portuguese display names.
 * Sorted alphabetically by Portuguese name.
 */
export const ISO3_COUNTRIES: readonly CountryOption[] = [
  { code: 'AFG', name: 'Afeganistão' },
  { code: 'ZAF', name: 'África do Sul' },
  { code: 'ALB', name: 'Albânia' },
  { code: 'DEU', name: 'Alemanha' },
  { code: 'AND', name: 'Andorra' },
  { code: 'AGO', name: 'Angola' },
  { code: 'AIA', name: 'Anguilla' },
  { code: 'ATA', name: 'Antártida' },
  { code: 'ATG', name: 'Antígua e Barbuda' },
  { code: 'SAU', name: 'Arábia Saudita' },
  { code: 'DZA', name: 'Argélia' },
  { code: 'ARG', name: 'Argentina' },
  { code: 'ARM', name: 'Armênia' },
  { code: 'ABW', name: 'Aruba' },
  { code: 'AUS', name: 'Austrália' },
  { code: 'AUT', name: 'Áustria' },
  { code: 'AZE', name: 'Azerbaijão' },
  { code: 'BHS', name: 'Bahamas' },
  { code: 'BGD', name: 'Bangladesh' },
  { code: 'BRB', name: 'Barbados' },
  { code: 'BHR', name: 'Barém' },
  { code: 'BEL', name: 'Bélgica' },
  { code: 'BLZ', name: 'Belize' },
  { code: 'BEN', name: 'Benim' },
  { code: 'BMU', name: 'Bermudas' },
  { code: 'BLR', name: 'Bielorrússia' },
  { code: 'BOL', name: 'Bolívia' },
  { code: 'BES', name: 'Bonaire, Santo Eustáquio e Saba' },
  { code: 'BIH', name: 'Bósnia e Herzegovina' },
  { code: 'BWA', name: 'Botsuana' },
  { code: 'BRA', name: 'Brasil' },
  { code: 'BRN', name: 'Brunei' },
  { code: 'BGR', name: 'Bulgária' },
  { code: 'BFA', name: 'Burquina Faso' },
  { code: 'BDI', name: 'Burundi' },
  { code: 'BTN', name: 'Butão' },
  { code: 'CPV', name: 'Cabo Verde' },
  { code: 'CMR', name: 'Camarões' },
  { code: 'KHM', name: 'Camboja' },
  { code: 'CAN', name: 'Canadá' },
  { code: 'QAT', name: 'Catar' },
  { code: 'KAZ', name: 'Cazaquistão' },
  { code: 'TCD', name: 'Chade' },
  { code: 'CHL', name: 'Chile' },
  { code: 'CHN', name: 'China' },
  { code: 'CYP', name: 'Chipre' },
  { code: 'COL', name: 'Colômbia' },
  { code: 'COM', name: 'Comores' },
  { code: 'COG', name: 'Congo (Brazzaville)' },
  { code: 'COD', name: 'Congo (Kinshasa)' },
  { code: 'PRK', name: 'Coreia do Norte' },
  { code: 'KOR', name: 'Coreia do Sul' },
  { code: 'CIV', name: 'Costa do Marfim' },
  { code: 'CRI', name: 'Costa Rica' },
  { code: 'HRV', name: 'Croácia' },
  { code: 'CUB', name: 'Cuba' },
  { code: 'CUW', name: 'Curaçao' },
  { code: 'DNK', name: 'Dinamarca' },
  { code: 'DJI', name: 'Djibuti' },
  { code: 'DMA', name: 'Dominica' },
  { code: 'EGY', name: 'Egito' },
  { code: 'SLV', name: 'El Salvador' },
  { code: 'ARE', name: 'Emirados Árabes Unidos' },
  { code: 'ECU', name: 'Equador' },
  { code: 'ERI', name: 'Eritreia' },
  { code: 'SVK', name: 'Eslováquia' },
  { code: 'SVN', name: 'Eslovênia' },
  { code: 'ESP', name: 'Espanha' },
  { code: 'SWZ', name: 'Essuatíni' },
  { code: 'USA', name: 'Estados Unidos' },
  { code: 'EST', name: 'Estônia' },
  { code: 'ETH', name: 'Etiópia' },
  { code: 'FJI', name: 'Fiji' },
  { code: 'PHL', name: 'Filipinas' },
  { code: 'FIN', name: 'Finlândia' },
  { code: 'FRA', name: 'França' },
  { code: 'GAB', name: 'Gabão' },
  { code: 'GMB', name: 'Gâmbia' },
  { code: 'GHA', name: 'Gana' },
  { code: 'GEO', name: 'Geórgia' },
  { code: 'SGS', name: 'Geórgia do Sul e Ilhas Sandwich do Sul' },
  { code: 'GIB', name: 'Gibraltar' },
  { code: 'GRD', name: 'Granada' },
  { code: 'GRC', name: 'Grécia' },
  { code: 'GRL', name: 'Groenlândia' },
  { code: 'GLP', name: 'Guadalupe' },
  { code: 'GUM', name: 'Guam' },
  { code: 'GTM', name: 'Guatemala' },
  { code: 'GGY', name: 'Guernsey' },
  { code: 'GUY', name: 'Guiana' },
  { code: 'GUF', name: 'Guiana Francesa' },
  { code: 'GIN', name: 'Guiné' },
  { code: 'GNQ', name: 'Guiné Equatorial' },
  { code: 'GNB', name: 'Guiné-Bissau' },
  { code: 'HTI', name: 'Haiti' },
  { code: 'HND', name: 'Honduras' },
  { code: 'HKG', name: 'Hong Kong' },
  { code: 'HUN', name: 'Hungria' },
  { code: 'YEM', name: 'Iêmen' },
  { code: 'ALA', name: 'Ilhas Åland' },
  { code: 'BVT', name: 'Ilha Bouvet' },
  { code: 'CXR', name: 'Ilha Christmas' },
  { code: 'IMN', name: 'Ilha de Man' },
  { code: 'HMD', name: 'Ilha Heard e Ilhas McDonald' },
  { code: 'NFK', name: 'Ilha Norfolk' },
  { code: 'CYM', name: 'Ilhas Cayman' },
  { code: 'CCK', name: 'Ilhas Cocos (Keeling)' },
  { code: 'COK', name: 'Ilhas Cook' },
  { code: 'FRO', name: 'Ilhas Faroé' },
  { code: 'FLK', name: 'Ilhas Malvinas' },
  { code: 'MNP', name: 'Ilhas Marianas do Norte' },
  { code: 'MHL', name: 'Ilhas Marshall' },
  { code: 'UMI', name: 'Ilhas Menores Distantes dos Estados Unidos' },
  { code: 'PCN', name: 'Ilhas Pitcairn' },
  { code: 'SLB', name: 'Ilhas Salomão' },
  { code: 'TCA', name: 'Ilhas Turks e Caicos' },
  { code: 'VIR', name: 'Ilhas Virgens Americanas' },
  { code: 'VGB', name: 'Ilhas Virgens Britânicas' },
  { code: 'IND', name: 'Índia' },
  { code: 'IDN', name: 'Indonésia' },
  { code: 'IRN', name: 'Irã' },
  { code: 'IRQ', name: 'Iraque' },
  { code: 'IRL', name: 'Irlanda' },
  { code: 'ISL', name: 'Islândia' },
  { code: 'ISR', name: 'Israel' },
  { code: 'ITA', name: 'Itália' },
  { code: 'JAM', name: 'Jamaica' },
  { code: 'JPN', name: 'Japão' },
  { code: 'JEY', name: 'Jersey' },
  { code: 'JOR', name: 'Jordânia' },
  { code: 'KWT', name: 'Kuweit' },
  { code: 'LAO', name: 'Laos' },
  { code: 'LSO', name: 'Lesoto' },
  { code: 'LVA', name: 'Letônia' },
  { code: 'LBN', name: 'Líbano' },
  { code: 'LBR', name: 'Libéria' },
  { code: 'LBY', name: 'Líbia' },
  { code: 'LIE', name: 'Liechtenstein' },
  { code: 'LTU', name: 'Lituânia' },
  { code: 'LUX', name: 'Luxemburgo' },
  { code: 'MAC', name: 'Macau' },
  { code: 'MKD', name: 'Macedônia do Norte' },
  { code: 'MDG', name: 'Madagascar' },
  { code: 'MYS', name: 'Malásia' },
  { code: 'MWI', name: 'Malaui' },
  { code: 'MDV', name: 'Maldivas' },
  { code: 'MLI', name: 'Mali' },
  { code: 'MLT', name: 'Malta' },
  { code: 'MAR', name: 'Marrocos' },
  { code: 'MTQ', name: 'Martinica' },
  { code: 'MUS', name: 'Maurício' },
  { code: 'MRT', name: 'Mauritânia' },
  { code: 'MYT', name: 'Mayotte' },
  { code: 'MEX', name: 'México' },
  { code: 'MMR', name: 'Mianmar' },
  { code: 'FSM', name: 'Micronésia' },
  { code: 'MOZ', name: 'Moçambique' },
  { code: 'MDA', name: 'Moldávia' },
  { code: 'MCO', name: 'Mônaco' },
  { code: 'MNG', name: 'Mongólia' },
  { code: 'MNE', name: 'Montenegro' },
  { code: 'MSR', name: 'Montserrat' },
  { code: 'NAM', name: 'Namíbia' },
  { code: 'NRU', name: 'Nauru' },
  { code: 'NPL', name: 'Nepal' },
  { code: 'NIC', name: 'Nicarágua' },
  { code: 'NER', name: 'Níger' },
  { code: 'NGA', name: 'Nigéria' },
  { code: 'NIU', name: 'Niue' },
  { code: 'NOR', name: 'Noruega' },
  { code: 'NCL', name: 'Nova Caledônia' },
  { code: 'NZL', name: 'Nova Zelândia' },
  { code: 'OMN', name: 'Omã' },
  { code: 'NLD', name: 'Países Baixos' },
  { code: 'PLW', name: 'Palau' },
  { code: 'PSE', name: 'Palestina' },
  { code: 'PAN', name: 'Panamá' },
  { code: 'PNG', name: 'Papua-Nova Guiné' },
  { code: 'PAK', name: 'Paquistão' },
  { code: 'PRY', name: 'Paraguai' },
  { code: 'PER', name: 'Peru' },
  { code: 'PYF', name: 'Polinésia Francesa' },
  { code: 'POL', name: 'Polônia' },
  { code: 'PRI', name: 'Porto Rico' },
  { code: 'PRT', name: 'Portugal' },
  { code: 'KEN', name: 'Quênia' },
  { code: 'KGZ', name: 'Quirguistão' },
  { code: 'KIR', name: 'Quiribati' },
  { code: 'GBR', name: 'Reino Unido' },
  { code: 'CAF', name: 'República Centro-Africana' },
  { code: 'CZE', name: 'República Tcheca' },
  { code: 'DOM', name: 'República Dominicana' },
  { code: 'REU', name: 'Reunião' },
  { code: 'ROU', name: 'Romênia' },
  { code: 'RWA', name: 'Ruanda' },
  { code: 'RUS', name: 'Rússia' },
  { code: 'ESH', name: 'Saara Ocidental' },
  { code: 'WSM', name: 'Samoa' },
  { code: 'ASM', name: 'Samoa Americana' },
  { code: 'BLM', name: 'São Bartolomeu' },
  { code: 'KNA', name: 'São Cristóvão e Névis' },
  { code: 'SMR', name: 'São Marinho' },
  { code: 'MAF', name: 'São Martinho (França)' },
  { code: 'SXM', name: 'São Martinho (Países Baixos)' },
  { code: 'SPM', name: 'São Pedro e Miquelão' },
  { code: 'STP', name: 'São Tomé e Príncipe' },
  { code: 'VCT', name: 'São Vicente e Granadinas' },
  { code: 'SHN', name: 'Santa Helena, Ascensão e Tristão da Cunha' },
  { code: 'LCA', name: 'Santa Lúcia' },
  { code: 'SEN', name: 'Senegal' },
  { code: 'SLE', name: 'Serra Leoa' },
  { code: 'SRB', name: 'Sérvia' },
  { code: 'SYC', name: 'Seicheles' },
  { code: 'SGP', name: 'Singapura' },
  { code: 'SYR', name: 'Síria' },
  { code: 'SOM', name: 'Somália' },
  { code: 'LKA', name: 'Sri Lanka' },
  { code: 'SDN', name: 'Sudão' },
  { code: 'SSD', name: 'Sudão do Sul' },
  { code: 'SWE', name: 'Suécia' },
  { code: 'CHE', name: 'Suíça' },
  { code: 'SUR', name: 'Suriname' },
  { code: 'SJM', name: 'Svalbard e Jan Mayen' },
  { code: 'THA', name: 'Tailândia' },
  { code: 'TWN', name: 'Taiwan' },
  { code: 'TJK', name: 'Tajiquistão' },
  { code: 'TZA', name: 'Tanzânia' },
  { code: 'ATF', name: 'Terras Austrais e Antárticas Francesas' },
  { code: 'IOT', name: 'Território Britânico do Oceano Índico' },
  { code: 'TLS', name: 'Timor-Leste' },
  { code: 'TGO', name: 'Togo' },
  { code: 'TKL', name: 'Tokelau' },
  { code: 'TON', name: 'Tonga' },
  { code: 'TTO', name: 'Trinidad e Tobago' },
  { code: 'TUN', name: 'Tunísia' },
  { code: 'TKM', name: 'Turcomenistão' },
  { code: 'TUR', name: 'Turquia' },
  { code: 'TUV', name: 'Tuvalu' },
  { code: 'UKR', name: 'Ucrânia' },
  { code: 'UGA', name: 'Uganda' },
  { code: 'URY', name: 'Uruguai' },
  { code: 'UZB', name: 'Uzbequistão' },
  { code: 'VUT', name: 'Vanuatu' },
  { code: 'VAT', name: 'Vaticano' },
  { code: 'VEN', name: 'Venezuela' },
  { code: 'VNM', name: 'Vietnã' },
  { code: 'WLF', name: 'Wallis e Futuna' },
  { code: 'ZMB', name: 'Zâmbia' },
  { code: 'ZWE', name: 'Zimbábue' },
] as const;

export function findCountryByCode(code: string): CountryOption | undefined {
  const normalized = code.trim().toUpperCase();
  return ISO3_COUNTRIES.find((c) => c.code === normalized);
}

export function isValidCountryCode(code: string): boolean {
  return findCountryByCode(code) !== undefined;
}
