import React from 'react';
import { afterEach, beforeEach, expect, it, vi } from 'vitest';
import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react';
import { api, ApiError } from '../src/lib/api';
import { FeedbackTriageDashboard } from '../src/components/feedback/feedback-triage-dashboard';
const report = { id: 'fb-1', category: 'BUG', message: 'Full original report text', status: 'PENDING', identifySelf: false, submitterEmail: 'ana@example.com', pagePath: '/settings', locale: 'pt-BR', appVersion: '1', adminNote: null, lastIssueError: null, createdAt: '2026-10-04T12:00:00Z' };
beforeEach(() => { vi.spyOn(api, 'get').mockResolvedValue({ items: [report, { ...report, id: 'fb-2', identifySelf: true }], total: 2 }); vi.spyOn(api, 'post').mockResolvedValue({ ...report, status: 'APPROVED', githubIssueUrl: 'https://github.com/example/repo/issues/1' }); });
afterEach(() => { cleanup(); vi.restoreAllMocks(); });
async function open() { render(<FeedbackTriageDashboard />); fireEvent.click(await screen.findByTestId('feedback-row-fb-1')); }
it('lists identities and hides anonymous identity', async () => { await open(); expect(screen.getByTestId('feedback-row-fb-1')).toHaveTextContent('Relato anônimo'); expect(screen.getByTestId('feedback-row-fb-2')).toHaveTextContent('Autor identificado'); expect(screen.queryByText('ana@example.com')).not.toBeInTheDocument(); expect(screen.getByText(report.message)).toBeInTheDocument(); });
it('approves with labels and displays the issue', async () => { await open(); fireEvent.change(screen.getByLabelText('Título da issue'), { target: { value: 'Valid issue title' } }); fireEvent.click(screen.getByRole('button', { name: 'Aprovar e abrir issue' })); await waitFor(() => expect(api.post).toHaveBeenCalledWith('/admin/feedback/fb-1/approve', { title: 'Valid issue title', labels: ['feedback', 'bug'], adminNote: undefined })); expect(await screen.findByRole('link', { name: 'Ver issue no GitHub' })).toBeInTheDocument(); });
it('keeps pending after GitHub failure and retries', async () => { vi.mocked(api.post).mockRejectedValueOnce(new ApiError(502, 'Bad Gateway', 'GitHub unavailable')); await open(); fireEvent.change(screen.getByLabelText('Título da issue'), { target: { value: 'Valid issue title' } }); fireEvent.click(screen.getByRole('button', { name: 'Aprovar e abrir issue' })); expect(await screen.findByTestId('feedback-issue-error')).toHaveTextContent('GitHub'); expect(screen.getByTestId('feedback-row-fb-1')).toHaveTextContent('Pendente'); fireEvent.click(screen.getByTestId('feedback-retry-approve')); await waitFor(() => expect(api.post).toHaveBeenCalledTimes(2)); });
it('requires reason and rejects', async () => { await open(); expect(screen.getByRole('button', { name: 'Rejeitar' })).toBeDisabled(); fireEvent.change(screen.getByLabelText('Motivo da rejeição'), { target: { value: 'Duplicate report' } }); fireEvent.click(screen.getByRole('button', { name: 'Rejeitar' })); await waitFor(() => expect(api.post).toHaveBeenCalledWith('/admin/feedback/fb-1/reject', { reason: 'Duplicate report' })); });
it('filters status and category', async () => { render(<FeedbackTriageDashboard />); await screen.findByTestId('feedback-row-fb-1'); fireEvent.change(screen.getByLabelText('Status'), { target: { value: 'APPROVED' } }); fireEvent.change(screen.getByLabelText('Categoria'), { target: { value: 'IDEA' } }); await waitFor(() => expect(api.get).toHaveBeenCalledWith('/admin/feedback', { params: { status: 'APPROVED', category: 'IDEA', take: 50, skip: 0 } })); });
